# Generated by Django 4.2.7 on 2023-11-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('loan_date', models.DateField()),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_principal_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_penalties_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('late_payment_penalties', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='loan_attachments/')),
                ('approved_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('test', models.CharField(blank=True, max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_products.loanproduct')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField()),
                ('principal_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalties_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
            options={
                'db_table': 'loan_repayments',
            },
        ),
    ]
