# Generated by Django 4.2.7 on 2023-11-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='test',
        ),
    ]
